name: MachineCraft
version: 1.0.0
author: Ome_R
main: com.ome_r.machinecraft.MachineCraft
commands:
  machinecraft:
    description: To be changed.
    aliases: [machine, mcraft]
    permission: machinecraft.admin